export const ISSUE_SCOPE_KEY = Object.freeze({
  map: "audit_scope_map",
  timeline: "audit_scope_timeline",
  archive: "audit_scope_archive",
  heroes: "audit_scope_heroes",
  homebrew: "audit_scope_homebrew",
  id: "audit_scope_id",
  routes: "audit_scope_routes",
});

export const ISSUE_CODE_KEY = Object.freeze({
  "duplicate-id": "audit_issue_duplicate_id",
  "blank-marker-title": "audit_issue_blank_marker_title",
  "blank-marker-description": "audit_issue_blank_marker_description",
  "blank-facts": "audit_issue_blank_facts",
  "image-caption-without-image": "audit_issue_image_caption_without_image",
  "long-title": "audit_issue_long_title",
  "suspicious-image-url": "audit_issue_suspicious_image_url",
  "heavy-data-url": "audit_issue_heavy_data_url",
  "blank-timeline-title": "audit_issue_blank_timeline_title",
  "blank-timeline-description": "audit_issue_blank_timeline_description",
  "long-sidebar-label": "audit_issue_long_sidebar_label",
  "blank-archive-group": "audit_issue_blank_archive_group",
  "blank-archive-title": "audit_issue_blank_archive_title",
  "blank-archive-description": "audit_issue_blank_archive_description",
  "blank-archive-full": "audit_issue_blank_archive_full",
  "missing-preview": "audit_issue_missing_preview",
  "missing-symbol": "audit_issue_missing_symbol",
  "long-image-label": "audit_issue_long_image_label",
  "blank-hero-group": "audit_issue_blank_hero_group",
  "blank-hero-group-subtitle": "audit_issue_blank_hero_group_subtitle",
  "blank-hero-title": "audit_issue_blank_hero_title",
  "blank-hero-role": "audit_issue_blank_hero_role",
  "blank-hero-description": "audit_issue_blank_hero_description",
  "blank-hero-full": "audit_issue_blank_hero_full",
  "missing-hero-portrait": "audit_issue_missing_hero_portrait",
  "blank-homebrew-category": "audit_issue_blank_homebrew_category",
  "blank-homebrew-title": "audit_issue_blank_homebrew_title",
  "blank-homebrew-summary": "audit_issue_blank_homebrew_summary",
  "blank-homebrew-content": "audit_issue_blank_homebrew_content",
  "missing-pinned-marker": "audit_issue_missing_pinned_marker",
  "route-unfinished": "audit_issue_route_unfinished",
  "route-out-of-bounds": "audit_issue_route_out_of_bounds",
});
